### ISSUE TITLE
TASK: Pages pre-launch ToDo

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-web#465]
**What needs to be done?**

(Work in progress, more items to be added)

PRE-LAUNCH ITEMS, in order of priority:

- [x] Video under "Connecting people & communities" block doesn't open
- [x] "Main Features" block isn't responsive
- [x]  Add a "Search" button to the top navigation
- [x]  Add a Google Translate button to the top navigation
- [x]  OKS: Team page: members's block should display their actual email address, not hide it behind a button
- [x] create /community page
- [x] /vision page: center the play button
- [x] fix /donate page: paypal logo, QR code, change details on the right-hand menu, remove the bottom block if unneeded
- [x] /about-us: fix padding between the end of the content and footer; links should be blue not black
- [x] create /get-involved/volunteer-translator page
- [x] create 4 /legal pages
- [x] fix homepage (+ shown on other pages) footer image scaling - stars should be visible
- [x] Create /projects page and subpages
- [x] redirect /dda to /projects/dda
- [x] /community: add the "What is a Civic Hacktivist" block from the original page, not sure how to transfer it as it's not an image
- [x] HC: https://github.com/citizenos/citizenos-web/issues/423 
- [x] HC: https://github.com/citizenos/citizenos-web/issues/420 
- [x] Frontpage: "Who uses our platform" chunk's "Learn more" links are not working
- [x] (SAME AS ABOVE) - Product page's "Who uses our platform" chunk "Learn more" links are not working
- [x] Visual hiccup here https://beta.citizenos.com/help/follow-up/
- [x] Paypal custom code for Donate page
- [x] Becca's [HC findings](https://docs.google.com/document/d/1oQ41SKQm4kNiRzaBkD28FX9fDs66ThGuy6VhYOopHxI/edit?usp=sharing)
- [x] Ensure proper HC integration with app.citizenos.com
- [x] Becca's [second web file](https://docs.google.com/document/d/1KBnxK_C1jhXR3Z9HGktHTDh4RkixT5aYDiS78XtBzKw/edit?pli=1) 
- [x] Layout issues from [screenshots in Slack chat](https://citizen-os.slack.com/archives/D04V8PKHKK7/p1687782456657859)
- [x] https://github.com/citizenos/citizenos-web/issues/468
- [x] https://github.com/citizenos/citizenos-web/issues/467
- [x] Thank on yes button for HC article
- [x] breadcrumns to be reverted back help>help>help and remove the old designed one
- [x] Send email to AWS for email restrictions
- [x] Set up feedback emails - additional server or else
- [x] All external "open in new tab" links are broken in Google Translate mode
- [ ] Test ALL pages on mobile + fix bugs
- [x] OKS: Change DDA cross-links between tabs to text

=========
INTERNAL LAUNCH
- [x] Desktop testing: team to test the website & file bugs for 2 working days
- [x] Mobile testing: team to test the website & file bugs for 2 working days
- [x] Fix any found crucial bugs
- [x] Exclude Rahvaalgatus stats https://github.com/citizenos/citizenos-web/issues/472 AND https://github.com/citizenos/citizenos-web/issues/358

=========
PUBLIC LAUNCH

**Post-launch checklist**
- [x] Plausible integration
- [x] HC breadcrumbs as in current web
- [ ] Create template page with all the template blocks
- [ ] Remove any accidental beta.citizenos.com links from the website
- [ ] General website search
- [ ] Projects section: add an icon, showing that that's an external link, to "Read more" buttons for projects which don't have a homepage with us
- [ ] Projects + News page: if you click outside of content, the selection of category disappears. It should stay active.
- [ ] HC search results section separation

**Comment by oksks** [comment]
Closing and moving any post-launch open items to a new ticket, as this one's getting out of hand with the number of tasks ))
