### ISSUE TITLE
TASK: Web post-launch ToDo (continuously updated)

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-web#479]
**What needs to be done?**

Priorities are listed from top down ⬇️

- [x] Make news blurb background yellow (both in live and draft versions)
- [x] Double CTA https://github.com/citizenos/citizenos-web/issues/480
- [x] Becca’s HC formatting notes https://github.com/citizenos/citizenos-web/issues/478
- [x] Remove any accidental beta.citizenos.com links from the website
- [x] Projects section: add an icon, showing that that's an external link, to "Read more" buttons for projects which don't have a homepage with us
- [x] Create template page with all the template blocks https://citizenos.com/wp-admin/post.php?post=1548&action=elementor
- [x] Projects + News page: if you click outside of content, the selection of category disappears. It should stay active.
- [x] Small globe icon to replace the Google Translate one https://github.com/citizenos/citizenos-web/issues/470 
- [x] Kevin’s web design notes - last item outstanding https://github.com/citizenos/citizenos-web/issues/474 
- [x] General website search
- [x] HC search results section separation
- [x] Handover: document all the necessary info/data/accesses regarding web management, for Oks + future dev (please make it dummy-proof so I'd be able to understand what's in it :D ) https://docs.google.com/spreadsheets/d/1korWh5OCPhSlkVseeHjT8Fhvjj62OVPmvvahqa52cjE/edit?usp=sharing access is only to Anett and Illmar at the moment
- [x] Indonesian site: in the absence of input from ID team, is there something you can prepare in the meantime? ID page URL? Something else? https://citizenos.com/id/
- [x] UPCOMING: New template blocks, to be developed and added to template page when Becca and Meelika have signed the design off and assigned to you (apx ~Sept 25) https://github.com/citizenos/citizenos-web/issues/483
- [x] Do a full round of web maintenance, right before you leave
- [x] Make an additional Elementor template from [this design](https://www.figma.com/file/eHBSunqUv10fMcWmiEEXiv/Website?type=design&node-id=2651-12561&mode=design&t=yN7fgLO2uWoFUFZv-4): a carousel, which would allow to add more blocks and click on left and right arrows to move between them: (Tried and tested with Becca on call, at the moment elementor is limited to style that block like that, will need a ACF pro plugin which will allow having repeater backend data options that can be pulled into a template and that template can be shown like that.)

<img width="739" alt="Screenshot 2023-09-14 at 12 44 38" src="https://github.com/citizenos/citizenos-web/assets/34126353/4f40dedb-ba1f-4795-b51e-a31844815859">

**Comment by devosama1** [comment]
![image](https://github.com/citizenos/citizenos-web/assets/56334857/2b7a3f06-d3f4-4bf1-b4ac-bff6675c8f87)

**Comment by devosama1** [comment]
Projects + News page: if you click outside of content, the selection of category disappears. It should stay active.

Above task i want to make a part of the new updates regarding the indonesia page. When i make new changes for that then i can update the outline effects. @oksks

**Comment by devosama1** [comment]
![image](https://github.com/citizenos/citizenos-web/assets/56334857/394cf180-0a75-4793-83fd-dfb09e1dff21)
![image](https://github.com/citizenos/citizenos-web/assets/56334857/d6bd0092-3d63-4b85-af7a-1115b32dde61)

@oksks @Agustinaiskandar To add project location, you can do so here. This will show as a text beside project listing. Part of Indonesia requirements.

The colors i used are the exact colors of Indonesia flag. Hope this is okay.

**Comment by devosama1** [comment]
@oksks @BeccaMelhuish  regarding the last task. At the moment it is not possible to create that with Elementor, i will implement a custom code solution for this. This could have been made possible with a ACF pro plugin, which would allow so much customization and its very compatible with Elementor blocks as well. Anyhow ill build and implement this. To change the content for that you will need to edit the code, i will share where i have implemented that and how you can update the content if needed.
